# Generated by Django 2.2.4 on 2019-11-19 10:38

from django.db import migrations


def get_owner_from_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_phone_pure=flat.owner_phone_pure)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(get_owner_from_flats, move_backward),
    ]
