# Generated by Django 2.2.4 on 2019-11-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20191119_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_link',
        ),
    ]
